baseURL = 'https://blog.gantz.ai/'
languageCode = 'en-us'
title = 'Gantz Blog'
theme = 'lowkey'
paginate = 10

[params]
  favicon = "favicon.ico"

[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    identifier = 'gantz'
    name = 'Gantz'
    url = 'https://gantz.ai'
    weight = 3
