baseURL = 'https://blog.gantz.ai/'
languageCode = 'en-us'
title = 'Gantz Blog'
theme = 'dream'
paginate = 10

[params]
author = "Gantz"
headerTitle = "Gantz Blog"
siteStartYear = 2025
lightTheme = "emerald"
darkTheme = "forest"
showTableOfContents = true

[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = false
