baseURL = 'https://blog.gantz.run/'
languageCode = 'en-us'
title = 'Gantz Blog'
theme = 'paper'

[params]
  color = 'linen'
  github = 'https://github.com/phukon'
  twitter = ''

[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    identifier = 'gantz'
    name = 'Gantz'
    url = 'https://gantz.run'
    weight = 3
